### PR TITLE
Cmake: when building for Max on the Mac, don't include the version nu…

### PR DESCRIPTION
**Pull request by tap**
…mber in the binary/install_name. Additionally, now copy the binaries for the core into a common location that can be easily copied/linked.  New "link.sh" script can be run to add sym links to this common location from the Jamoma Max package structure.

### CODE REVIEW

**Comment by tap** [comment]
Hmmm...  I guess Travis is failing but it doesn't tell me why :-/

**Comment by avilleret** [comment]
according to https://travis-ci.org/jamoma/JamomaMax/builds/99350939#L240 it fails copying a dylib into the `support` folder, maybe we need to manually create this folder __before__ copying

**Comment by avilleret** [comment]
hum, folder should be created with : https://github.com/jamoma/JamomaMax/blob/8da51f30874513ced9f26d44702832681fde198c/library/CMakeLists.txt#L170-L175
but it seems it is not.
So I guess there might be an execution order issue.

**Comment by tap** [comment]
Hi @avilleret -- I think this is ready now if you are comfortable with it.  It's little ugly, but I simply disabled the copy step when running on Travis.

**Pull request merged**
